eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
  server:
    #eureka的自我保护
    enable-self-preservation: true

spring:
  application:
    name: eureka

#
#server:
#  port: 8761
management:
  context-path: /
